---
title: Dot Pattern Plots
date: last-modified
page-layout: full
code-fold: true
code-tools: true
execute: 
  warning: false
  eval: true
---


```{r}
pacman::p_load(dplyr,purrr,tidyr,ggplot2, here, patchwork, conflicted)
conflict_prefer_all("dplyr", quiet = TRUE)
source("read_22.R")
```


```{r fig.width=10,fig.height=10}
#| fig-width: 11
dot <- dCat %>% ungroup() %>% filter(id=="1.nrep",(Pattern.Type=="Prototype" | Pattern.Type=="New-Low"))%>%  select(typeCount,Category,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,x6,y6,x7,y7,x8,y8,x9,y9) 
nTrial=nrow(dot);
dotx=c(dot$x1,dot$x2,dot$x3,dot$x4,dot$x5,dot$x6,dot$x7,dot$x8,dot$x9); doty=c(dot$y1,dot$y2,dot$y3,dot$y4,dot$y5,dot$y6,dot$y7,dot$y8,dot$y9)
dotFrame <- data.frame(typeCount=rep(dot$typeCount,each=9),Trial=rep(seq(1:nTrial),each=9),Category=factor(rep(dot$Category,each=9)),x=dotx,y=doty)
pg <- ggplot(dotFrame,aes(dotx,doty,col=Category))+geom_point()+facet_grid(typeCount~Category)

pg

```




```{r fig.width=5,fig.height=5}
#| eval: false
#| include: false

nTrial=200;
proto <- dCat %>% ungroup() %>% filter(id=="1.nrep",Pattern.Type=="Prototype")%>%  select(Category,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,x6,y6,x7,y7,x8,y8,x9,y9) 
nTrial=3;
dot=proto
dotx=c(dot$x1,dot$x2,dot$x3,dot$x4,dot$x5,dot$x6,dot$x7,dot$x8,dot$x9); doty=c(dot$y1,dot$y2,dot$y3,dot$y4,dot$y5,dot$y6,dot$y7,dot$y8,dot$y9)
dotFrame <- data.frame(Trial=rep(seq(1:nTrial),each=9),Category=factor(rep(dot$Category,each=9)),x=dotx,y=doty)
pg <- ggplot(dotFrame,aes(dotx,doty,col=Category))+geom_point()+facet_grid(Trial~Category)



nl <- dCat %>% ungroup() %>% filter(id=="1.nrep",Pattern.Type=="New-Low")%>%  select(Category,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,x6,y6,x7,y7,x8,y8,x9,y9) 
nTrial=nrow(nl)
dot=nl
dotx=c(dot$x1,dot$x2,dot$x3,dot$x4,dot$x5,dot$x6,dot$x7,dot$x8,dot$x9); doty=c(dot$y1,dot$y2,dot$y3,dot$y4,dot$y5,dot$y6,dot$y7,dot$y8,dot$y9)
dotFrame <- data.frame(Trial=rep(seq(1:nTrial),each=9),Category=factor(rep(dot$Category,each=9)),x=dotx,y=doty)
pl <- ggplot(dotFrame,aes(dotx,doty,col=Category))+geom_point()+facet_grid(Trial~Category)

gridExtra::grid.arrange(pg,pl)
pg
pl
```








```{r}
#| eval: false
#| include: false


dot <- dCatTrain[1,] %>% ungroup() %>%  select(x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,x6,y6,x7,y7,x8,y8,x9,y9) 
dot %>% ggplot()+geom_point(x1,y1)+geom_point(x2,y2)+geom_point(x3,y3)
dotx=c(dot$x1,dot$x2,dot$x3,dot$x4,dot$x5,dot$x6,dot$x7,dot$x8,dot$x9); doty=c(dot$y1,dot$y2,dot$y3,dot$y4,dot$y5,dot$y6,dot$y7,dot$y8,dot$y9)
dotFrame <- data.frame(dotx,doty)
ggplot(dotFrame,aes(dotx,doty))+geom_point()


```
