---
title: Fixed Prototype Pilot
date: last-modified
#page-layout: full
format:
  html: 
    grid:
      sidebar-width: 220px
      body-width: 1200px
      margin-width: 170px
      gutter-width: 1.0rem
toc: true
#toc-location: right
toc-depth: 4
code-fold: true
code-tools: true
lightbox: true
execute: 
  warning: false
  eval: true
---






<details>
<summary><b> Mingjia's Report {{< fa file-lines >}} </b></summary>

```{=html}
<embed src="/reports/technical_report_v1.pdf" width="1000px" height="900px" />
```
</details>




```{r}

pacman::p_load(dplyr,purrr,tidyr,ggplot2, here, patchwork, conflicted, knitr,grateful)
conflict_prefer_all("dplyr", quiet = TRUE)

fp24 <- readRDS(here("data","fixed_proto24.rds"))



theme_nice_b <- function() {
  theme_minimal(base_family = "Manrope") +
    theme(
      panel.grid.minor = element_blank(),
      plot.title = element_text(family = "Manrope Extrabold", face = "plain", size = rel(1.55)),
      plot.subtitle = element_text(family = "Manrope Medium", face = "plain", size = rel(1.2)),
      axis.title = element_text(family = "Manrope SemiBold", face = "plain", size = rel(1)),
      axis.title.x = element_text(hjust = .5),
      axis.title.y = element_text(hjust = .5),
      axis.text = element_text(family = "Manrope Light", face = "plain", size = rel(0.9)),
      strip.text = element_text(
        family = "Manrope", face = "bold",
        size = rel(1.2), hjust = 0
      ),
      legend.position = "top",
      legend.text = element_text(family = "Manrope Light", face = "plain", size = rel(1.3)),
      strip.background = element_rect(fill = "grey90", color = NA)
    )
}




theme_set(theme_nice_b())

yt <- round(seq(0,1,length.out=7), 2)
xt <- seq(1,10,1)
eg <- list(geom_hline(yintercept = c(.33, .66),linetype="dashed", alpha=.5),
           scale_y_continuous(breaks=yt,limits=c(0,1)),
           scale_x_continuous(breaks=xt))


```



```{r}
#| layout-ncol: 2 


fp24 |> filter(Phase==2) |>
  group_by(sbjCode, condit, Pattern_Token) |>
  summarize(Corr=mean(Corr)) |>
  ggplot(aes(x=Pattern_Token, y=Corr, fill=condit, group=condit)) +  
  stat_summary(geom="bar",fun=mean, position=position_dodge())+
  stat_summary(geom="errorbar", fun.data=mean_se, position=position_dodge()) +
  labs(title="Testing Performance - Fixed Proto.", y="Accuracy") 



fp24 |> filter(Phase==2) |>
  group_by(sbjCode, condit, Pattern_Token) |>
  summarize(Corr=mean(Corr)) |>
  ggplot(aes(x=condit, y=Corr, fill=Pattern_Token, group=Pattern_Token)) +  
  stat_summary(geom="bar",fun=mean, position=position_dodge())+
  stat_summary(geom="errorbar", fun.data=mean_se, position=position_dodge()) +
  labs(title="Testing Performance - Fixed Proto.", y="Accuracy") 





fp24 |> filter(Phase==1) |>
  group_by(sbjCode, condit, Pattern_Token,Block) |>
  summarize(Corr=mean(Corr),.groups="keep") |>
  ggplot(aes(x=Block, y=Corr, col=condit, group=condit)) +  
  stat_summary(geom="line",fun=mean)+
  stat_summary(geom="errorbar", fun.data=mean_se,width=.1) +
  labs(title="Training Performance.", y="Accuracy") +
  #eg +  
  theme(legend.position = "top") + eg
  
```