

```{r setup}
pacman::p_load(dplyr,purrr,tidyr,ggplot2, here, patchwork, conflicted, knitr,grateful)
conflict_prefer_all("dplyr", quiet = TRUE)
#source(here::here("R/read_24.R"))

#https://fonts.google.com/specimen/Manrope
# ~/Library/Fonts
theme_nice <- function() {
  theme_minimal(base_family = "Manrope") +
    theme(
      panel.grid.minor = element_blank(),
      plot.title = element_text(family = "Manrope Extrabold", face = "plain", size = rel(1.35)),
      plot.subtitle = element_text(family = "Manrope Medium", face = "plain", size = rel(1.2)),
      axis.title = element_text(family = "Manrope SemiBold", face = "plain", size = rel(1)),
      axis.title.x = element_text(hjust = .5),
      axis.title.y = element_text(hjust = .5),
      axis.text = element_text(family = "Manrope Light", face = "plain", size = rel(0.8)),
      strip.text = element_text(
        family = "Manrope", face = "bold",
        size = rel(.75), hjust = 0
      ),
      strip.background = element_rect(fill = "grey90", color = NA)
    )
}

theme_nice_dist <- function() {
  theme_nice() +
    theme(
      panel.grid = element_blank(),
      panel.spacing.x = unit(10, units = "pt"),
      axis.ticks.x = element_line(linewidth = 0.25),
      axis.text.y = element_blank()
    )
}

theme_set(theme_nice())
```



```{r}
#| eval: false
#| cache: FALSE

library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(forcats)
library(purrr)
library(ggplot2)
library(ggthemes)
library(glue)
library(knitr)

set.seed(42)

knitr::opts_template$set(
  code = list(echo = TRUE, eval = FALSE)
)

# load font for plots
.font <- "Source Sans Pro"
if (!(.font %in% sysfonts::font_families()))
  sysfonts::font_add_google(.font, .font)
showtext::showtext_auto()

# set custom plot theme
theme_set(theme_bw(base_size = 14, base_family = .font))
theme_update(panel.grid = element_blank(),
             strip.background = element_blank(),
             legend.key = element_blank(),
             panel.border = element_blank(),
             axis.line = element_line(),
             strip.text = element_text(face = "bold"))

# set options for default color and fill scales
options("ggplot2.discrete.colour"   = ggthemes::scale_colour_ptol   )
options("ggplot2.continuous.colour" =  viridis::scale_colour_viridis)
options("ggplot2.discrete.fill"     = ggthemes::scale_fill_ptol     )
options("ggplot2.continuous.fill"   =  viridis::scale_fill_viridis  )

# solarized colors for individual elements (like reference lines)
pal <- list(
  grey   = "#93a1a1",
  red    = "#dc322f",
  blue   = "#268bd2",
  purple = "#6c71c4"
)

# from https://bookdown.org/yihui/rmarkdown-cookbook/font-color.html
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    glue("\\textcolor{<color>}{<x>}", .open = "<", .close = ">")
  } else if (knitr::is_html_output()) {
    glue("<span style='color: var(--{stringr::str_sub(color, 2)});'>{x}</span>")
  } else x
}
```